import { escape } from './common.js';
export const restaurantUrl = id => '/restaurant.html?id=' + Number(id);
export function restaurantCard(r, { recommendation = false } = {}) {
  const url = restaurantUrl(r.restaurant_id);
  return `<article class="restaurant"><a class="card-photo" href="${url}" aria-label="View ${escape(r.name)}"><img src="${escape(r.cover_image || '/assets/indian-meal.png')}" alt="${escape(r.cuisine_type)} cuisine" loading="lazy" width="700" height="420"><span class="photo-status ${r.is_open ? 'open' : ''}">${r.is_open ? 'Open for pickup' : 'Closed now'}</span></a><div class="restaurant-content"><div class="restaurant-head"><h3><a href="${url}">${escape(r.name)}</a></h3>${recommendation ? `<div class="score">${r.recommendation_score}<small>match / 100</small></div>` : ''}</div><p class="meta">${escape(r.cuisine_type)} &middot; ${escape(r.price_range)} &middot; <i data-lucide="star"></i> ${r.average_rating ?? 'New'} <span>(${r.rating_count || 0} reviews)</span></p><p class="small muted">${r.distance_metres !== undefined ? `${r.distance_metres} m &middot; ${r.walk_minutes} min walk` : escape(r.address)}</p><div class="badges"><span class="badge neutral"><i data-lucide="shopping-bag"></i> Pickup ${r.pickup_minutes || 20}-${(r.pickup_minutes || 20) + 10} min</span>${r.vegan_friendly ? '<span class="badge">Vegan options</span>' : r.vegetarian_friendly ? '<span class="badge">Vegetarian options</span>' : ''}</div>${(r.promotion || (r.promotion_active && r.promotion_text)) ? `<p class="offer"><i data-lucide="tag"></i> ${escape(r.promotion || r.promotion_text)}</p>` : ''}<div class="restaurant-actions"><a class="button secondary" href="${url}">View restaurant <i data-lucide="arrow-right"></i></a></div>${recommendation ? scoreDetails(r) : ''}</div></article>`;
}
function scoreDetails(r) {
  const weights = { proximity: 35, cuisine: 20, dietary: 15, price: 10, rating: 15, promotion: 5 };
  const labels = { proximity: 'Proximity', cuisine: 'Cuisine', dietary: 'Dietary fit', price: 'Budget', rating: 'Rating', promotion: 'Promotion' };
  return '<details><summary>Why this recommendation?</summary>' + Object.entries(r.score_breakdown).map(([key, value]) => `<div class="score-row"><span>${labels[key]}</span><meter min="0" max="${weights[key]}" value="${value}">${value}</meter><span>${value} / ${weights[key]}</span></div>`).join('') + '<p class="small muted">Rounded contributions. Offers add up to 5 points.</p></details>';
}
